[package]
name = "cli-client"
version = "0.1.0"
edition = "2024"
description = ""
license = "MIT OR Apache-2.0"
readme = "README.md"
publish = false


[[bin]]
name = "simplicity-dex"
path = "src/bin/main.rs"

[dependencies]

